# Enable firewall by using:
# $ gcloud compute firewall-rules create gke-main-allow-nginx-http --network=main --allow=tcp:32065 --source-ranges=i<public_ipv4>/32 --target-tags=<node-pool-tag>

kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: kube-public
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    nodePort: 32065

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: kube-public
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80
